PROTOCOL_VERSION = 10
MAGIC = 0x42b33f00

FEATURE_ENCRYPTION = 0x01
FEATURE_COMPRESSION = 0x02
FEATURES = { FEATURE_ENCRYPTION : 'encryption', FEATURE_COMPRESSION : 'compression' }

DATASTREAMPROTOCOL = 0x02
DATASTREAMFEATURES = 0

PROTOCOLS = { DATASTREAMPROTOCOL : 'datastream' }

LIST_END = 0x80000000

from .protocol import QuasselClientProtocol